parameters:
#    user.example.class: Rabot\UserBundle\Example

services:
#    user.example:
#        class: %user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    UserBundle_user.registration.form.type:
        class: Cms\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: cms_userbundle_user_registration }