contenu:
    resource: "@ContenuBundle/Resources/config/routing.yml"
    prefix:   /

gestion_contenu:
    resource: "@ContenuBundle/Resources/config/routing_admin.yml"
    prefix:   /gestion

article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /

gestion_article:
    resource: "@ArticleBundle/Resources/config/routing_admin.yml"
    prefix:   /gestion

page:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /

gestion_page:
    resource: "@PageBundle/Resources/config/routing_admin.yml"
    prefix:   /gestion

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

gestion_user:
    resource: "@UserBundle/Resources/config/routing_admin.yml"
    prefix:   /gestion

domaine:
    resource: "@DomaineBundle/Resources/config/routing.yml"
    prefix:   /

domaine_administration:
    resource: "@DomaineBundle/Resources/config/routing_admin.yml"
    prefix:   /gestion
