<?php

namespace Cms\ContenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
	public function findAll()
	{
		$publier = 1;
		
		$qb = $this->createQueryBuilder('s')
				   ->Where('s.publier = :publier')
				   ->setParameter('publier', $publier)


				   ;

		return $qb->getQuery()
            	  ->getResult();

	}
}
