domaine_admin_homepage:
    pattern:  /
    defaults: { _controller: DomaineBundle:Admin:index }

domaine_admin_menu_homepage:
    pattern:  /menu_homepage
    defaults: { _controller: DomaineBundle:Admin:menu_homepage }

domaine_admin_ajouter_menu:
    pattern:  /ajouter_menu
    defaults: { _controller: DomaineBundle:Admin:ajouter_menu }

domaine_admin_modifier_nom_menu:
    pattern:  /modifier_nom_menu/{idmenu}
    defaults: { _controller: DomaineBundle:Admin:modifier_nom_menu }

domaine_admin_supprimer_page_menu:
    pattern:  /supprimer_page_menu/{idmenu}
    defaults: { _controller: DomaineBundle:Admin:supprimer_page_menu }






fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile