domaine_homepage:
    pattern:  /
    defaults: { _controller: DomaineBundle:Default:index }

domaine_homepage_inserer_logo_site:
    pattern: /inserer-logo_site
    defaults: { _controller: DomaineBundle:Default:inserer_logo_site}


domaine_homepage_inserer_menu:
    pattern: /inserer-menu
    defaults: { _controller: DomaineBundle:Default:inserer_menu}

domaine_homepage_inserer_menu_page:
    pattern: /inserer-menu-page
    defaults: { _controller: DomaineBundle:Default:inserer_menu_page}

domaine_homepage_inserer_contact:
    pattern: /inserer-contact
    defaults: { _controller: DomaineBundle:Default:inserer_contact}

domaine_homepage_inserer_reseaux_sociaux:
    pattern: /inserer-reseaux-sociaux
    defaults: { _controller: DomaineBundle:Default:inserer_reseaux_sociaux}

domaine_voir_page:
    pattern: /consulter-page/{idpage}
    defaults: { _controller: DomaineBundle:Default:consulter_page}

domaine_voir_sous_menu:
    pattern: /consulter-sous-menu/{idsousmenu}
    defaults: { _controller: DomaineBundle:Default:consulter_sous_menu}

domaine_voir_evenement:
    pattern: /consulter-evenement/{idevenement}
    defaults: { _controller: DomaineBundle:Default:consulter_evenement}

domaine_voir_article:
    pattern: /consulter-article/{idarticle}
    defaults: { _controller: DomaineBundle:Default:consulter_article}