domaine_homepage:
    pattern:  /
    defaults: { _controller: DomaineBundle:Default:index }


domaine_homepage_inserer_menu:
    pattern: /inserer-menu
    defaults: { _controller: DomaineBundle:Default:inserer_menu}

domaine_voir_page:
    pattern: /consulter-page/{idpage}
    defaults: { _controller: DomaineBundle:Default:consulter_page}