parameters:
#    domaine.example.class: Rabot\DomaineBundle\Example

services:
#    domaine.example:
#        class: %domaine.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
