Page_admin_homepage:
    pattern: /page_homepage
    defaults: { _controller: PageBundle:Admin:page_homepage}

Page_admin_voir_une_page:
    pattern: /voir_une_page/{idpage}
    defaults: { _controller: PageBundle:Admin:voir_une_page}

Page_admin_ajouter_une_page:
    pattern: /ajouter_une_page
    defaults: { _controller: PageBundle:Admin:ajouter_une_page}

Page_admin_modifier_une_page:
    pattern: /modifier_une_page/{idpage}
    defaults: { _controller: PageBundle:Admin:modifier_une_page}

Page_admin_supprimer_une_page:
    pattern: /supprimer_une_page/{idpage}
    defaults: { _controller: PageBundle:Admin:supprimer_une_page}

Page_admin_ajouter_image_carousel_page:
    pattern: /ajouter_image_carousel_page/{idpage}
    defaults: { _controller: PageBundle:Admin:ajouter_image_carousel_page}

Page_admin_modifier_image_carousel_page:
    pattern: /modifier_image_carousel_page/{idphoto}
    defaults: { _controller: PageBundle:Admin:modifier_image_carousel_page}

Page_admin_supprimer_image_carousel_page:
    pattern: /supprimer_image_carousel_page/{idphoto}
    defaults: { _controller: PageBundle:Admin:supprimer_image_carousel_page}


Page_admin_ajouter_section_page:
    pattern: /ajouter_section_page/{idpage}
    defaults: { _controller: PageBundle:Admin:ajouter_section_page}

