Page_admin_homepage:
    pattern: /page_homepage
    defaults: { _controller: PageBundle:Admin:page_homepage}

Page_admin_voir_une_page:
    pattern: /voir_une_page/{idpage}
    defaults: { _controller: PageBundle:Admin:voir_une_page}

Page_admin_ajouter_une_page:
    pattern: /ajouter_une_page
    defaults: { _controller: PageBundle:Admin:ajouter_une_page}

Page_admin_modifier_une_page:
    pattern: /modifier_une_page/{idpage}
    defaults: { _controller: PageBundle:Admin:modifier_une_page}

Page_admin_supprimer_une_page:
    pattern: /supprimer_une_page/{idpage}
    defaults: { _controller: PageBundle:Admin:supprimer_une_page}



Page_admin_ajouter_image_carousel_page:
    pattern: /ajouter_image_carousel_page/{idpage}
    defaults: { _controller: PageBundle:Admin:ajouter_image_carousel_page}

Page_admin_modifier_image_carousel_page:
    pattern: /modifier_image_carousel_page/{idphoto}
    defaults: { _controller: PageBundle:Admin:modifier_image_carousel_page}

Page_admin_supprimer_image_carousel_page:
    pattern: /supprimer_image_carousel_page/{idphoto}
    defaults: { _controller: PageBundle:Admin:supprimer_image_carousel_page}



Page_admin_ajouter_image_couverture_page:
    pattern: /ajouter_image_couverture_page/{idpage}
    defaults: { _controller: PageBundle:Admin:ajouter_image_couverture_page}



Page_admin_ajouter_section_page:
    pattern: /ajouter_section_page/{idpage}
    defaults: { _controller: PageBundle:Admin:ajouter_section_page}

Page_admin_modifier_section_page:
    pattern: /modifier_section_page/{idsection}
    defaults: { _controller: PageBundle:Admin:modifier_section_page}

Page_admin_supprimer_section_page:
    pattern: /supprimer_section_page/{idsection}
    defaults: { _controller: PageBundle:Admin:supprimer_section_page}

Page_admin_supprimer_categories_section_page:
    pattern: /supprimer_categories_section_page/{idsection}
    defaults: { _controller: PageBundle:Admin:supprimer_categories_section_page}




Page_admin_voir_sous_menu_page:
    pattern: /voir_sous_menu_page/{idsousmenu}
    defaults: { _controller: PageBundle:Admin:voir_sous_menu_page}


Page_admin_ajouter_sous_menu_page:
    pattern: /ajouter_sous_menu_page/{idpage}
    defaults: { _controller: PageBundle:Admin:ajouter_sous_menu_page}

Page_admin_modifier_sous_menu_page:
    pattern: /modifier_sous_menu_page/{idsousmenu}
    defaults: { _controller: PageBundle:Admin:modifier_sous_menu_page}

Page_admin_supprimer_sous_menu_page:
    pattern: /supprimer_sous_menu_page/{idsousmenu}
    defaults: { _controller: PageBundle:Admin:supprimer_sous_menu_page}

Page_admin_ajouter_image_carousel_sous_menu_page:
    pattern: /ajouter_image_carousel_sous_menu_page/{idsousmenu}
    defaults: { _controller: PageBundle:Admin:ajouter_image_carousel_sous_menu_page}

Page_admin_modifier_image_carousel_sous_menu_page:
    pattern: /modifier_image_carousel_sous_menu_page/{idphoto}
    defaults: { _controller: PageBundle:Admin:modifier_image_carousel_sous_menu_page}

Page_admin_supprimer_image_carousel_sous_menu_page:
    pattern: /supprimer_image_carousel_sous_menu_page/{idphoto}
    defaults: { _controller: PageBundle:Admin:supprimer_image_carousel_sous_menu_page}


Page_admin_ajouter_section_sous_menu_page:
    pattern: /ajouter_section_sous_menu_page/{idsousmenu}
    defaults: { _controller: PageBundle:Admin:ajouter_section_sous_menu_page}

Page_admin_modifier_section_sous_menu_page:
    pattern: /modifier_section_sous_menu_page/{idsection}
    defaults: { _controller: PageBundle:Admin:modifier_section_sous_menu_page}

Page_admin_supprimer_section_sous_menu_page:
    pattern: /supprimer_section_sous_menu_page/{idsection}
    defaults: { _controller: PageBundle:Admin:supprimer_section_sous_menu_page}

Page_admin_supprimer_categorie_section_sous_menu_page:
    pattern: /supprimer_categorie_section_sous_menu_page/{idsection}
    defaults: { _controller: PageBundle:Admin:supprimer_categorie_section_sous_menu_page}

