evenement_admin_homepage:
    pattern:  /evenement_homepage
    defaults: { _controller: ContenuBundle:Admin:evenement_homepage }


evenement_admin_voir_un_evenement:
    pattern:  /voir_un_evenement/{idevenement}
    defaults: { _controller: ContenuBundle:Admin:voir_un_evenement }

evenement_admin_ajouter_un_evenement:
    pattern:  /ajouter_un_evenement
    defaults: { _controller: ContenuBundle:Admin:ajouter_un_evenement }

evenement_admin_modifier_un_evenement:
    pattern:  /modifier_un_evenement/{idevenement}
    defaults: { _controller: ContenuBundle:Admin:modifier_un_evenement }

evenement_admin_supprimer_un_evenement:
    pattern:  /supprimer_un_evenement/{idevenement}
    defaults: { _controller: ContenuBundle:Admin:supprimer_un_evenement }


evenement_admin_ajouter_photo_evenement:
    pattern:  /ajouter_photo_evenement/{idevenement}
    defaults: { _controller: ContenuBundle:Admin:ajouter_photo_evenement }

evenement_admin_modifier_photo_evenement:
    pattern:  /modifier_photo_evenement/{idphoto}
    defaults: { _controller: ContenuBundle:Admin:modifier_photo_evenement }

evenement_admin_supprimer_photo_evenement:
    pattern:  /supprimer_photo_evenement/{idphoto}
    defaults: { _controller: ContenuBundle:Admin:supprimer_photo_evenement }



service_admin_homepage:
    pattern:  /service_homepage
    defaults: { _controller: ContenuBundle:Admin:service_homepage }


service_admin_voir_un_service:
    pattern:  /voir_un_service/{idservice}
    defaults: { _controller: ContenuBundle:Admin:voir_un_service }

service_admin_ajouter_un_service:
    pattern:  /ajouter_un_service
    defaults: { _controller: ContenuBundle:Admin:ajouter_un_service }

service_admin_modifier_un_service:
    pattern:  /modifier_un_service/{idservice}
    defaults: { _controller: ContenuBundle:Admin:modifier_un_service }

service_admin_supprimer_un_service:
    pattern:  /supprimer_un_service/{idservice}
    defaults: { _controller: ContenuBundle:Admin:supprimer_un_service }


equipe_admin_homepage:
    pattern:  /equipe_homepage
    defaults: { _controller: ContenuBundle:Admin:equipe_homepage }


equipe_admin_voir_une_equipe:
    pattern:  /voir_une_equipe/{idequipe}
    defaults: { _controller: ContenuBundle:Admin:voir_une_equipe }

equipe_admin_ajouter_une_equipe:
    pattern:  /ajouter_une_equipe
    defaults: { _controller: ContenuBundle:Admin:ajouter_une_equipe }

equipe_admin_modifier_une_equipe:
    pattern:  /modifier_une_equipe/{idequipe}
    defaults: { _controller: ContenuBundle:Admin:modifier_une_equipe }

equipe_admin_supprimer_une_equipe:
    pattern:  /supprimer_une_equipe/{idequipe}
    defaults: { _controller: ContenuBundle:Admin:supprimer_une_equipe }





