article_admin_homepage:
    pattern:  /article_homepage
    defaults: { _controller: ArticleBundle:Admin:article_homepage }

article_admin_page_categorie:
   pattern: /page_categorie
   defaults: { _controller: ArticleBundle:Admin:page_categorie}

article_admin_ajouter_une_categorie:
   pattern: /ajouter_une_categorie
   defaults: { _controller: ArticleBundle:Admin:ajouter_une_categorie}

article_admin_modifier_une_categorie:
   pattern: /modifier_une_categorie/{idCategorie}
   defaults: { _controller: ArticleBundle:Admin:modifier_une_categorie}

article_admin_supprimer_une_categorie:
   pattern: /supprimer_une_categorie/{idCategorie}
   defaults: { _controller: ArticleBundle:Admin:supprimer_une_categorie}


article_admin_choix_categorie:
    pattern:  /choix_categorie/{idarticle}
    defaults: { _controller: ArticleBundle:Admin:choix_categorie }



article_admin_voir_un_article:
    pattern:  /voir_un_article/{idarticle}
    defaults: { _controller: ArticleBundle:Admin:voir_un_article }

article_admin_ajouter_un_article:
    pattern:  /ajouter_un_article
    defaults: { _controller: ArticleBundle:Admin:ajouter_un_article }

article_admin_modifier_un_article:
    pattern:  /modifier_un_article/{idarticle}
    defaults: { _controller: ArticleBundle:Admin:modifier_un_article }

article_admin_supprimer_un_article:
    pattern:  /supprimer_un_article/{idarticle}
    defaults: { _controller: ArticleBundle:Admin:supprimer_un_article }


article_admin_ajouter_photo_article:
    pattern:  /ajouter_photo_article/{idarticle}
    defaults: { _controller: ArticleBundle:Admin:ajouter_photo_article }

article_admin_modifier_photo_article:
    pattern:  /modifier_photo_article/{idphoto}
    defaults: { _controller: ArticleBundle:Admin:modifier_photo_article }

article_admin_supprimer_photo_article:
    pattern:  /supprimer_photo_article/{idphoto}
    defaults: { _controller: ArticleBundle:Admin:supprimer_photo_article }



