parameters:
#    article.example.class: Cms\ArticleBundle\Example

services:
#    article.example:
#        class: %article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
