<?php

namespace Cms\DomaineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SousMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousMenuRepository extends EntityRepository
{
}
