<?php

namespace Cms\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function getArticlesPublies()
	{
		$publier = 1;

		$qb = $this->createQueryBuilder('a')
				   ->Where('a.publier = :publier')
				   ->setParameter('publier', $publier)

				   ;

		return $qb->getQuery()
            	  ->getResult();

	}
}
