<?php

namespace Cms\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

	public function getArticlesPublies()
	{
		$publier = 1;

		$qb = $this->createQueryBuilder('a')
				   ->Where('a.publier = :publier')
				   ->setParameter('publier', $publier)
				   ->andWhere('a.type = :article')
				   ->setParameter('article', 'Article')
				   ;

		return $qb->getQuery()
            	  ->getResult();

	}

	public function getPublicationsPublies()
	{
		$publier = 1;

		$qb = $this->createQueryBuilder('a')
				   ->Where('a.publier = :publier')
				   ->setParameter('publier', $publier)
				   ->andWhere('a.type = :publication')
				   ->setParameter('publication', 'Publication')
				   ;

		return $qb->getQuery()
            	  ->getResult();

	}

}
